# Generated by Django 3.1.14 on 2023-07-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_albums', '0003_auto_20230729_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['disc', 'order']},
        ),
        migrations.AddField(
            model_name='track',
            name='disc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('album', 'disc', 'order')},
        ),
    ]
